### ISSUE TITLE
can't detect language

### ISSUE THREAD

**Issue by chaeya** [hamonikr/systemback#1]
OS : HamoniKR 4.0 beta , Linuxmint 20, Ubuntu 20.04

프로그램 실행 후 사용중인 언어 환경을 가져오지 못하는 버그

**Comment by bdh1993** [comment]
systemback.pro 파일에
lang/systemback_ko_KR.ts \
추가
빌드 후 언어 설정 확인하였음

**Comment by bdh1993** [comment]
systemback.pro 파일에
lang/systemback_ko_KR.ts
추가
빌드 후 언어 설정 확인하였음
